### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luaharfbuzz#1]
* harfbuzz-gem: https://github.com/jslabovitz/harfbuzz-gem
* Lua-C interactions: 
  - http://lua-users.org/wiki/UserDataWithPointerExample
  - http://lua-users.org/wiki/BindingWithMetatableAndClosures
  - https://john.nachtimwald.com/2014/07/12/wrapping-a-c-library-in-lua/

**Comment by michal-h21** [comment]
The [example](https://github.com/jslabovitz/harfbuzz-gem/blob/master/examples/example.rb) from `harfbuzz-gem` is interesting. Especially font face functions (it could be more efficient to cache it, instead of creating new face with font data for each word, as it happens now). 

And also `buffer.guess_segment_properties`, which guess script, language and direction from the text. I want to do something similar in Lua callback, which would process the nodes before shaping and set correct language and direction depending on unicode class they belongs. So Latin text in Arabic paragraph wouldn't need to be denoted in some macro which sets correct direction, font and language.

**Comment by deepakjois** [comment]
Here is a preliminary sketch of API that I am thinking of in code form. This will evolve, and ofcourse things like features and segment properties will need to be incorporated.

```lua
local harfbuzz = require 'harfbuzz'

-- report version
print(harfbuzz.version)

-- list shapers
print(harfbuzz.shapers)

-- initialize blob
local blob = harfbuzz.Blob.new(…)
print(blob:length())

-- initialize buffer
local buf = harfbuzz.Buffer.new(…)
buf:add(…)
print(buf:length())

-- initialize font
local font1 = harfbuzz.Font.new(file,index)
local font2 = harfbuzz.Font.from_blob(blob,index) -- Maybe just use this, and have a from_file method in Blob
print(font1:upem())

-- shape
glyphs = harfbuzz.shape(font, buf, options)
```

**Comment by michal-h21** [comment]
On Wed, Dec 2, 2015 at 1:07 PM, Deepak Jois <notifications@github.com>
wrote:

> Here is a preliminary sketch of API that I am thinking of in code form.
> This will evolve, and ofcourse things like features and segment properties
> will need to be incorporated.
>
local harfbuzz = require 'harfbuzz'
> -- report versionprint(harfbuzz.version)
> -- list shapersprint(harfbuzz.shapers)
> -- initialize bloblocal blob = harfbuzz.Blob.new(…)print(blob:length())
> -- initialize bufferlocal buf = harfbuzz.Buffer.new(…)
> buf:add(…)print(buf:length())
> -- initialize fontlocal font1 = harfbuzz.Font.new(file,index)local font2 = harfbuzz.Font.from_blob(blob,index) -- Maybe just use this, and have a from_file method in Blob
>
> Maybe just use something like

  font, index = harfbuzz.Font.new(data_string)?

**Comment by deepakjois** [comment]
After the initial repo setup, I just finished coding up the first type in the list above, the `harfbuzz.Blob`, along with tests etc.

LuaRocks packaging is also done. So now it’s just a matter of wrapping all the other Harfbuzz types with Lua bindings. Hopefully, it will be done soon.

**Comment by deepakjois** [comment]
I had forgotten about the `hb_face_t` type in the API design spec above. I have added it as `harfbuzz.Face`.

```
local f = harfbuzz.Face.new('fonts/notonastaliq.ttf')
print(f:get_upem())
```

**Comment by michal-h21** [comment]
Not really api related, but I've setup simple test file for LuaLaTeX, see  https://github.com/michal-h21/luaharfbuzz-luatex-test 

The output from test string used in Makefile is 

<img src="http://i.imgur.com/OqefiXa.png" />

I am not sure whether it's correct, given the fact that we don't take direction nor language and script into account yet.

**Comment by deepakjois** [comment]
This is pretty accurate. You can easily compare this output with Harfbuzz’s output by running Harfbuzz’s `hb-shape` tool.

Here is what I ran
```
hb-view  --font-funcs=ot --shapers=ot  --output-format=png --output-file=out.png  ~/Downloads/NotoNastaliqUrdu-unhinted/NotoNastaliqUrdu-Regular.ttf "یہ"  
```

And here is what I got

![out](https://cloud.githubusercontent.com/assets/5342/11564997/06b978bc-9a02-11e5-836a-5d4da6a7b13e.png)

Good stuff!

**Comment by michal-h21** [comment]
Yeah, it seems that values of `x_offset` and `y_offset` can be used
directly in `xoffset` and `yoffset` node fields, after dimension
conversion. Width, height and depth are saved by fontloader, so we probably
don't have to set them explicitly?

**Comment by deepakjois** [comment]
The width, height and x/y-bearings come from the glyph extents. We can control whether to return it via some sort of options flag. That way, clients that need it can ask for it, and others can choose not to.

**Comment by deepakjois** [comment]
With 932e2f7, the basic API is now complete. Ofcourse there is lots more to be done, like shapers, additional member functions etc. But it is possible to do basic shaping that matches the output of the `hb-shape` tool. So I am closing this ticket, and tracking API additions in separate tickets.

@michal-h21 Note that the `harfbuzz._shape` is deprecated now. It is possible to do the same thing using the wrapped API types and the `harfbuzz.shape` method (see [example]). Another thing is that the library should to be loaded using `require 'harfbuzz'` and not `require 'luaharfbuzz'` (as some of your sample code does). I will keep `harfbuzz._shape` around for a while, but I hope to remove it as soon as possible. So let me know once you have modified your code.

[example]:https://github.com/deepakjois/luaharfbuzz/blob/master/examples/core_types.lua
