### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luaharfbuzz#11]
- [x] basic example that showcases all the core types and methods.
- [ ] example that writes to a PDF file.
- [x] example of a LuaTeX document using _luaharfbuzz_ to do shaping.
- [ ] example of a string (shaped using _luaharfbuzz_) rasterized to an image.
- [ ] CLI tool that mimics `hb-shape` Harfbuzz tool.

**Comment by michal-h21** [comment]
I've updated LuaTeX examples in [luatex-harfbuzz-shaper](https://github.com/michal-h21/luatex-harfbuzz-shaper/tree/master/examples)

**Comment by deepakjois** [comment]
On Thu, Dec 10, 2015 at 6:19 PM, Michal Hoftich <notifications@github.com>
wrote:

> I've updated LuaTeX examples in luatex-harfbuzz-shaper
> <https://github.com/michal-h21/luatex-harfbuzz-shaper/tree/master/examples>
>
>
>
I have linked to the project on the wiki here:
https://github.com/deepakjois/luaharfbuzz/wiki#projects-using-luaharfbuzz

Let me know if you have a better suggestion.

**Comment by michal-h21** [comment]
> I have linked to the project on the wiki here:
> https://github.com/deepakjois/luaharfbuzz/wiki#projects-using-luaharfbuzz
>
> Let me know if you have a better suggestion.
>
> No, that's fine, I think. BTW, have you seen
https://github.com/michal-h21/luatex-harfbuzz-shaper/issues/5 ?

**Comment by deepakjois** [comment]
Added a basic plain LuaTeX example in 78ea619e24f809a571a96c031a7cf56d67557918. It’s very basic and does not seem to work with Amiri. Need to debug

**Comment by deepakjois** [comment]
Closing this. Does not seem super important. I am primarily using it with LuaTeX, and [luatex-harfbuzz](https://github.com/deepakjois/luaharfbuzz) is the place where all the examples for that can be found.
