### ISSUE TITLE
cluster index differs from that of hb-shape

### ISSUE THREAD

**Issue by dohyunkim** [deepakjois/luaharfbuzz#22]
When I issue a command like this:
```
hb-shape /Library/Fonts/AppleGothic.ttf 가나다
```
the output is:
```
[gid2651=0+1000|gid2942=1+1000|gid3083=2+1000]
```
As shown, cluster indices are 0, 1, and 2.

But when I try a lua file:
```lua
local harfbuzz = require('harfbuzz')
local serpent  = require('serpent')

-- Harfbuzz API Version
print("Harfbuzz API version", harfbuzz.version())

-- harfbuzz.Face
local face = harfbuzz.Face.new('/Library/Fonts/AppleGothic.ttf')

-- harfbuzz.Font
local font = harfbuzz.Font.new(face)

-- harfbuzz.Buffer
local text = "가나다" -- U+AC00 U+B098 U+B2E4
local buf = harfbuzz.Buffer.new()
buf:add_utf8(text)

-- harfbuzz.shape (Shapes text)
print("\nShaping '"..text.."' set with AppleGothic")
harfbuzz.shape(font, buf, { language = "KOR", script = "hang", direction = "ltr" })

local glyphs = buf:get_glyph_infos_and_positions()
print("No. of glyphs", #glyphs)
print(serpent.block(glyphs, {comment = false}))
```
the output is:
```
Harfbuzz API version	1.1.2

Shaping '가나다' set with AppleGothic
No. of glyphs	3
{
  {
    cluster = 0,
    codepoint = 2651,
    x_advance = 1000,
    x_offset = 0,
    y_advance = 0,
    y_offset = 0
  },
  {
    cluster = 3,
    codepoint = 2942,
    x_advance = 1000,
    x_offset = 0,
    y_advance = 0,
    y_offset = 0
  },
  {
    cluster = 6,
    codepoint = 3083,
    x_advance = 1000,
    x_offset = 0,
    y_advance = 0,
    y_offset = 0
  }
}
```
Here the cluster indices are 0, 3, and 6. 
I wonder whether this is an expected behaviour.

**Comment by deepakjois** [comment]
Here is the script that is used to generate test data for comparing luaharfbuzz’s output with the output from `hb-shape`:
https://github.com/deepakjois/luaharfbuzz/blob/master/scripts/generate_hb_shape_json.sh

Note the flags being used: `--font-funcs=ot --utf8-clusters --no-glyph-names --shapers=ot`

If the output from hb-shape used with the flags above and luaharfbuzz don’t match up, I would consider that a bug.

Here are the results of my tests, invoking `hb-shape` with different flags against your input:

```
hb-shape /Library/Fonts/AppleGothic.ttf 가나다
[gid2651=0+1000|gid2942=1+1000|gid3083=2+1000]

hb-shape --font-funcs=ot --utf8-clusters --no-glyph-names --shapers=ot /Library/Fonts/AppleGothic.ttf 가나다
[2651=0+1000|2942=3+1000|3083=6+1000]

hb-shape --font-funcs=ot  --no-glyph-names --shapers=ot /Library/Fonts/AppleGothic.ttf 가나다
[2651=0+1000|2942=1+1000|3083=2+1000]
```

As you can see `--utf8-clusters` is the flag that seems to make the difference. I can’t recall setting something in the code that explicitly that does this.

As for `--font-funcs=ot` and `--shapers=ot`, that is something I am explicitly setting here: 
https://github.com/deepakjois/luaharfbuzz/blob/3e30a3d8d80542ae4c97455646bf421826fab5e2/src/luaharfbuzz/font.c#L18

I will update this issue when I figure out how the luaharfbuzz code implicitly has the behaviour equivalent to `--utf8-clusters`. I am not sure why this is at the moment.

**Comment by deepakjois** [comment]
I looked at the source code for the `hb-shape` tool in the Harfbuzz source tree.

It appears that the output from Harfbuzz is a raw index into the buffer. If the `--utf8-clusters` flag is passed in, the index is just passed through. However, if the flag is not set, the tool does some extra calculations to provide a different set of indices that correspond to the position of the unicode character in the input string.

So I suppose luaharfbuzz is passing on the glyph positions as expected. If the client requires it, they can perform their own calculations and make adjustments to the cluster indices.

Does that answer your question? If this is  behaviour a requirement for you?

**Comment by dohyunkim** [comment]
Thanks a lot. Now I understand.

Then it would be great if you provide an interface to [hb_buffer_add_codepoints](https://github.com/behdad/harfbuzz/blob/master/src/hb-buffer.cc#L1590). 

In LuaTeX's node processing stage, everyting is already in unicode codepoints. So it seems to be waste of resources to convert them to utf8 text and to recalculate cluster indices again.

**Comment by deepakjois** [comment]
@dohyunkim I have made a new issue #23, and added some questions/comments. Let’s continue the discussion there.

Closing this now.
