### ISSUE TITLE
Add hb_buffer_add_codepoints

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luaharfbuzz#23]
@dohyunkim has requested for an interface to `hb_buffer_add_codepoints`. See #22 for more context.

There are a few questions around how this could be exposed on the luaharfbuzz side.

The second argument to hb_buffer_add_codepoints is an array of  `hb_codepoint_t`, which is just a typedef of `uint32_t` (32-bit unsigned int type).

I don’t know the best way to represent Unicode codepoints in Lua. As an initial proposal, we could do something like this:

```lua
local codepoints = { 0xAC00, 0xB098, 0xB2E4 }  -- U+AC00 U+B098 U+B2E4
local buf = harfbuzz.Buffer.new()
buf:add_codepoints(codepoints) -- item_offset and item_length will be optional arguments, defaulting to 0 and -1 respectively
```

@khaledhosny, do you have any suggestions or thoughts?

@dohyunkim, will this serve your needs?

**Comment by michal-h21** [comment]
`char` field in LuaTeX glyph nodes contains unicode codepoint. At the moment, we convert them to characters using Selene unicode library, which is contained in LuaTeX in `luatex-harfbuzz-shaper`. The table with characters is then concatenated to string which is shaped by Luaharfbuzz. So I guess we are ready to skip this step and just pass table with codepoints to the buffer.

**Comment by deepakjois** [comment]
From the latest LuaTeX manual, it seems the `char` field is a number type. So the proposal I made above  should work. In the C code, I will need to extract the codepoints, cast them to `hb_codepoint_t`, and put them in an array to pass on to `hb_buffer_add_codepoints`.

**Comment by khaledhosny** [comment]
I’m no Lua expert, but the proposed API seems fine.

**Comment by deepakjois** [comment]
Added a pull request, #24. Tests seem to work as expected, with cluster indices reporting the codepoint index.

**Comment by deepakjois** [comment]
@khaledhosny and I am neither a C expert nor a Lua expert. I am actually just a bit concerned about all the typecasting I am doing from lua based number types to Harfbuzz based number types. Regarding this specific issue, I am getting a lua number via `luaL_checkinteger` which is technically a `ptrdiff` type, and casting it to `hb_codepoint_t` which is a `uint32_t` type. I hope that isn’t too problematic.

At some point, I need to better understanding casting of number types in C to make sure I know what I am doing.

**Comment by khaledhosny** [comment]
Neither I. I just do the casting and hope for the best :)

**Comment by dohyunkim** [comment]
I've just tested the new functionality and it works great. Thanks a lot.
