### ISSUE TITLE
Fix LuaTeX example with Amiri

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luaharfbuzz#25]
Using the shaping code with Amiri fails badly (see full log below for details). But the things I noticed:

* It seems that no glue nodes are being produced. The font backmap isn’t able to map the Amiri glyph for blank space to the `0x20` character.
* There is some problem writing the Amiri glyphs to the PDF (see all the `bad raw byte to print` errors below). Strangely, it seems related to the problem above, but I can’t say for sure why. Needs more investigation.

@khaledhosny, I realise it is too much to expect you to look at some code that I wrote to figure out what is wrong. But if you get a clue by taking a quick look at the output below, the [font loading code](https://github.com/deepakjois/luaharfbuzz/blob/78ea619e24f809a571a96c031a7cf56d67557918/examples/luatex/harfbuzz_setup.lua#L48) or the [node processing code](https://github.com/deepakjois/luaharfbuzz/blob/78ea619e24f809a571a96c031a7cf56d67557918/examples/luatex/harfbuzz_setup.lua#L149), please do let me know.

```
$> cd examples/luatex
$> luatex --fmt=plain urdu_amiri.tex

This is LuaTeX, Version beta-0.87.1 (TeX Live 2016/dev)  (format=plain 2015.12.27)  31 DEC 2015 16:06
**urdu_amiri.tex
(./urdu_amiri.tex (./setup.tex)
BUILDPAGE_FILTER new_graf
No. of nodes: 218
<local_par> <hlist(3)> ک ِ ت ن ے <glue(0)> ب ر س <glue(0)> ہ و ے ٔ <
glue(0)> ک ہ <glue(0)> ہ م <glue(0)> ن ے <glue(0)> ق ِ س م ت <glue(0)
> س ے <glue(0)> ا ی ک <glue(0)> ب ا ز ی <glue(0)> ل گ ا ئ ی <glue(
0)> ت ھ ی ۔ <glue(0)> ا ی ک <glue(0)> ا ِ ق ر ا ر <glue(0)> ک ِ 
ی ا <glue(0)> ت ھ ا ۔ <glue(0)> پ ر ت ِ گ ی ا <glue(0)> ک ی <glue
(0)> ت ھ ی ۔ ا ب <glue(0)> و ق ت <glue(0)> آ ی ا <glue(0)> ک ہ <gl
ue(0)> ہ م <glue(0)> ا ُ س <glue(0)> ک و <glue(0)> پ و ر ا <glue(0)> 
ک ر ی ں ۔ <glue(0)> ب ِ ل ک ُ ل <glue(0)> پ و ر ی <glue(0)> ت 
و <glue(0)> ش ا ی د <glue(0)> ا ب <glue(0)> ب ھ ی <glue(0)> ن ہ <glu
e(0)> ہ و ، <glue(0)> ل ی ک ِ ن <glue(0)> پ ھ ِ ر <glue(0)> ب ھ 
ی <glue(0)> ا ی ک <glue(0)> ب ڑ ی <glue(0)> م ن ز ِ ل <glue(0)> پ 
و ر ی <glue(0)> ہ و ئ ی <glue(0)> ، <glue(0)> ہ م <glue(0)> و ہ ا 
ں <glue(0)> پ ہ ُ ن چ ے ۔ <penalty(0)> <glue(15)> 
direction is: TRT
fontid is 51
paragraph can be shaped by Harfbuzz
No. of nodes after shaping: 218
Overfull \hbox (232.80096pt too wide) in paragraph at lines 16--17
[]\amiri 
warning  (print): bad raw byte to print (c=618), skipped
ِ
warning  (print): bad raw byte to print (c=463), skipped

warning  (print): bad raw byte to print (c=4747), skipped

warning  (print): bad raw byte to print (c=4767), skipped
 
warning  (print): bad raw byte to print (c=812), skipped

warning  (print): bad raw byte to print (c=846), skipped
س 
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=768), skipped
ۓ 
warning  (print): bad raw byte to print (c=3173), skipped

warning  (print): bad raw byte to print (c=3197), skipped
 
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=660), skipped
 
warning  (print): bad raw byte to print (c=4411), skipped

warning  (print): bad raw byte to print (c=4431), skipped
 
warning  (print): bad raw byte to print (c=504), skipped
ِ
warning  (print): bad raw byte to print (c=736), skipped

warning  (print): bad raw byte to print (c=666), skipped

warning  (print): bad raw byte to print (c=381), skipped
 
warning  (print): bad raw byte to print (c=4349), skipped

warning  (print): bad raw byte to print (c=4346), skipped
 ا
warning  (print): bad raw byte to print (c=435), skipped

warning  (print): bad raw byte to print (c=600), skipped
 
warning  (print): bad raw byte to print (c=416), skipped

warning  (print): bad raw byte to print (c=347), skipped
زی 
warning  (print): bad raw byte to print (c=649), skipped

warning  (print): bad raw byte to print (c=3061), skipped

warning  (print): bad raw byte to print (c=3092), skipped

warning  (print): bad raw byte to print (c=3368), skipped

warning  (print): bad raw byte to print (c=3458), skipped
 
warning  (print): bad raw byte to print (c=422), skipped

warning  (print): bad raw byte to print (c=4497), skipped

warning  (print): bad raw byte to print (c=780), skipped
۔ ا
warning  (print): bad raw byte to print (c=435), skipped

warning  (print): bad raw byte to print (c=600), skipped
 اِ
warning  (print): bad raw byte to print (c=504), skipped

warning  (print): bad raw byte to print (c=694), skipped
ار 
warning  (print): bad raw byte to print (c=1276), skipped
ِ
warning  (print): bad raw byte to print (c=1320), skipped

warning  (print): bad raw byte to print (c=347), skipped
 
warning  (print): bad raw byte to print (c=422), skipped

warning  (print): bad raw byte to print (c=4497), skipped

warning  (print): bad raw byte to print (c=347), skipped
۔ 
warning  (print): bad raw byte to print (c=810), skipped

warning  (print): bad raw byte to print (c=846), skipped

warning  (print): bad raw byte to print (c=422), skipped
ِ
warning  (print): bad raw byte to print (c=2216), skipped

warning  (print): bad raw byte to print (c=2261), skipped

warning  (print): bad raw byte to print (c=347), skipped
 
warning  (print): bad raw byte to print (c=3353), skipped

warning  (print): bad raw byte to print (c=3458), skipped
 
warning  (print): bad raw byte to print (c=422), skipped

warning  (print): bad raw byte to print (c=4497), skipped

warning  (print): bad raw byte to print (c=780), skipped
۔اب و
warning  (print): bad raw byte to print (c=504), skipped

warning  (print): bad raw byte to print (c=381), skipped
 آ
warning  (print): bad raw byte to print (c=435), skipped

warning  (print): bad raw byte to print (c=347), skipped
 
warning  (print): bad raw byte to print (c=3173), skipped

warning  (print): bad raw byte to print (c=3197), skipped
 
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=660), skipped
 اُس 
warning  (print): bad raw byte to print (c=618), skipped

warning  (print): bad raw byte to print (c=768), skipped
 
warning  (print): bad raw byte to print (c=414), skipped

warning  (print): bad raw byte to print (c=768), skipped
را 
warning  (print): bad raw byte to print (c=1809), skipped

warning  (print): bad raw byte to print (c=1827), skipped

warning  (print): bad raw byte to print (c=1544), skipped

warning  (print): bad raw byte to print (c=1548), skipped
۔ 
warning  (print): bad raw byte to print (c=416), skipped
ِ
warning  (print): bad raw byte to print (c=655), skipped

warning  (print): bad raw byte to print (c=3062), skipped
ُ
warning  (print): bad raw byte to print (c=3087), skipped
 
warning  (print): bad raw byte to print (c=414), skipped

warning  (print): bad raw byte to print (c=768), skipped
ری 
warning  (print): bad raw byte to print (c=422), skipped

warning  (print): bad raw byte to print (c=768), skipped
 
warning  (print): bad raw byte to print (c=728), skipped

warning  (print): bad raw byte to print (c=347), skipped

warning  (print): bad raw byte to print (c=1068), skipped

warning  (print): bad raw byte to print (c=1076), skipped
 اب 
warning  (print): bad raw byte to print (c=416), skipped

warning  (print): bad raw byte to print (c=4497), skipped

warning  (print): bad raw byte to print (c=780), skipped
 
warning  (print): bad raw byte to print (c=419), skipped

warning  (print): bad raw byte to print (c=579), skipped
 
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=768), skipped
، 
warning  (print): bad raw byte to print (c=649), skipped

warning  (print): bad raw byte to print (c=476), skipped

warning  (print): bad raw byte to print (c=636), skipped
ِ
warning  (print): bad raw byte to print (c=668), skipped
 
warning  (print): bad raw byte to print (c=414), skipped

warning  (print): bad raw byte to print (c=4497), skipped
ِ
warning  (print): bad raw byte to print (c=694), skipped
 
warning  (print): bad raw byte to print (c=416), skipped

warning  (print): bad raw byte to print (c=4497), skipped

warning  (print): bad raw byte to print (c=780), skipped
 ا
warning  (print): bad raw byte to print (c=435), skipped

warning  (print): bad raw byte to print (c=600), skipped
 
warning  (print): bad raw byte to print (c=812), skipped

warning  (print): bad raw byte to print (c=833), skipped
ی 
warning  (print): bad raw byte to print (c=663), skipped

warning  (print): bad raw byte to print (c=1649), skipped

warning  (print): bad raw byte to print (c=1678), skipped
ِل 
warning  (print): bad raw byte to print (c=414), skipped

warning  (print): bad raw byte to print (c=768), skipped
ری 
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=768), skipped

warning  (print): bad raw byte to print (c=3368), skipped

warning  (print): bad raw byte to print (c=3458), skipped
 ، 
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=660), skipped
 و
warning  (print): bad raw byte to print (c=584), skipped

warning  (print): bad raw byte to print (c=347), skipped
ں 
warning  (print): bad raw byte to print (c=3601), skipped

warning  (print): bad raw byte to print (c=3666), skipped
ُ
warning  (print): bad raw byte to print (c=460), skipped

warning  (print): bad raw byte to print (c=577), skipped

warning  (print): bad raw byte to print (c=4345), skipped
۔ |

\hbox(11.48926+5.8252)x540.60236, direction TRT
.\localpar
..\localinterlinepenalty=0
..\localbrokenpenalty=0
..\localleftbox=null
..\localrightbox=null
.\hbox(0.0+0.0)x0.0, direction TRT
.\amiri 
warning  (print): bad raw byte to print (c=618), skipped

.\amiri ِ
.\amiri 
warning  (print): bad raw byte to print (c=463), skipped

.etc.

BUILDPAGE_FILTER box
POST_LINEBREAK
BUILDPAGE_FILTER hmode_par
BUILDPAGE_FILTER vmode_par
BUILDPAGE_FILTER penalty
HPACK
VPACK
VPACK
HPACK
VPACK
warning  (pdf backend): forcing decimal digits to 4
[1{/Users/deepak/code/personal/luatex/luatexminimal/texmf/fonts/map/pdftex.map}]
BUILDPAGE_FILTER after_output)<../../fonts/amiri-regular.ttf>
Output written on urdu_amiri.pdf (1 page, 61308 bytes).

PDF statistics: 13 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 131072)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

**Comment by khaledhosny** [comment]
I don’t really have much of clue, it have been a while since I checked LuaTeX internals and it seems so much have changed, so I can’t even tell if most of this code is conceptually correct or not.

**Comment by deepakjois** [comment]
No problem, let me try StackExchange :)

**Comment by deepakjois** [comment]
@khaledhosny This maybe unrelated, but I am looking at the glyph and character indexes for Amiri font. In the output below: The `codepoint` is the glyph id value I get from Harfbuzz, and the backmap is the `character` that maps to the glyph id (whatever that means, i am not sure at the moment).

Two points:

* I am expecting glyph id `0x3` to map to `0x20` (the blank space character), but instead it maps to `0xa0` which is contradicting the logic in my code. What I see is that there is an extra bit set
* Moreover, `backmap` values such as `0x110248`, `0x110300` seem to be pretty big for LuaTeX, and cause it to throw error in this file on line 291 when printing to PDF file:
https://foundry.supelec.fr/scm/viewvc.php/trunk/source/texk/web2c/luatexdir/tex/printing.w?annotate=5624&root=luatex 

Do the `backmap` values below make any sense to you?

Output:
```
codepoint: 0x229, backmap: 0x6cc
codepoint: 0x3, backmap: 0xa0
codepoint: 0x8cf, backmap: 0x110248
codepoint: 0x987, backmap: 0x110300
codepoint: 0x13af, backmap: 0x110d28
codepoint: 0x1409, backmap: 0x110d82
codepoint: 0x3, backmap: 0xa0
```

**Comment by deepakjois** [comment]
Ok, I was able to narrow down the problem to the discrepancy in the backmap for glyph `0x3`, which instead of mapping to `0x20`, maps to `0xa0`. Moreover, it seems that `0xa0` is the codepoint for NO-BREAK SPACE.

So, it seems that the shaping for Amiri is actively substituting NO-BREAK SPACE for SPACE. Is that correct, @khaledhosny?

**Comment by deepakjois** [comment]
Posted this on StackExchange: http://tex.stackexchange.com/questions/285363/strange-output-with-luatex-s-fontloader-library

**Comment by deepakjois** [comment]
@michal-h21 Thanks for your answer on StackExchange. I realised that there is yet another method to intercept glyphs corresponding to spaces, and add glue instead. I could just check the `cluster` field returned by Harfbuzz for each glyph, and then use that to index into the original codepoints I sent to Harfbuzz. See 633dc18.

It remains to be seen if the assumption I am making (that a space character in input will produce only one glyph after shaping) is a safe one. I hope there isn’t some strange font out there that generates multiple glyphs for spaces or something exotic like that.

**Comment by michal-h21** [comment]
Yes, this method seems reasonable, only as I said on TeX.sx, beware of various space types: 

    \documentclass{article}
    \usepackage{luacode}
    \begin{luacode*}
    local glue_id = node.id "glue"
    local glyph_id = node.id "glyph"
    local penalty_id = node.id "penalty"
    local utfchar = unicode.utf8.char
    local onept = tex.sp "1pt"
    local function clb(head)
      local t = {}
      for n in node.traverse(head) do
        if n.id == glyph_id then
          t[#t+1] = utfchar(n.char)
        elseif n.id == glue_id then
          print(table.concat(t))
          t = {}
          local spec = n.spec
          local width = spec.width / onept
          local stretch = spec.stretch / onept
          local shrink = spec.shrink /onept
          print("glue type: ",n.subtype, width, stretch, shrink)
        elseif n.id == penalty_id then
          print("penalty", n.penalty)
        end
      end
      return head
    end
    luatexbase.add_to_callback("pre_linebreak_filter", clb, "print spaces")
    \end{luacode*}
    \begin{document}
    
    hello world~there\,are\quad various\qquad space\ types
    
    \end{document}

**Comment by deepakjois** [comment]
@michal-h21 You are right, a more complex implementation will need to account for all kinds of spaces. 

It seems the basic technique, i.e., using the cluster value to map back to the original context is still applicable. We can also keep info about the kind of glue that needs to be inserted in a separate table, indexed with the same cluster value.

**Comment by khaledhosny** [comment]
Amiri does not do any space to no break space substitution, however Amiri’s cmap table maps space and no break space characters to the same glyph id, and knowing the brokenness LuaTeX’s font loader, I’d not be surprised if this is confusing it in some way.

Also no assumptions should be mad about how space character will end up in the output glyphs, fonts can do all sorts of unusual stuff, see for example https://bugzilla.mozilla.org/show_bug.cgi?id=1212668. But I think checking the cluster values should be safe, especially if you set the buffer cluster level to two (which I recommend any way). You should probably use the width of the space as the natural width of the glue and may be make the stretch and shrink relative to it, i case the font is kerning the space or changing its width in any way.

I don’t recommend shaping words individually as it will break many fonts, unless you make sure the font has no layout features that involve the space character (which is doable, Firefox and Chrome do it using HarfBuzz APIs).

**Comment by deepakjois** [comment]
@khaledhosny Thanks for the tip about cluster levels. There seems to be very little documentation about it. I posted to the Harfbuzz mailing list asking about it, since it is probably of general interest.

I created #26 and #27 as followup items from this discussion. So, closing this now.
