### ISSUE TITLE
Make luaharbuzz buildable with Harfbuzz shipped inside TeXLive source tree

### ISSUE THREAD

**Issue by michal-h21** [deepakjois/luaharfbuzz#4]
Just reminder about David's idea to use Harbuzz library shipped with XeTeX. I am not sure whether it's possible, I can't find the library in the TeX tree, maybe it is included in the XeTeX binary?

_Updated by @deepakjois_:
- Harfbuzz source in TeXLive: https://www.tug.org/svn/texlive/trunk/Build/source/libs/harfbuzz/

**Comment by deepakjois** [comment]
Currently, the Makefile uses whatever version is available on the system, and I don’t see a reason to change that.

What can be done is that if and when we are ready to ship this as part of TeX Live, we can have a separate build procedure catering specifically for inclusion in the TeX Live tree.

**Comment by michal-h21** [comment]
As I said, I even don't know whether it is possible to use this library,
and even if it was, I am not sure if our bindings could be included in TL,
the maintainers don't want to include binary modules. So Luarocks is
probably a better solution.

**Comment by deepakjois** [comment]
Yes, LuaRocks also has some guidelines on Makefiles, so will need to follow those:
https://github.com/keplerproject/luarocks/wiki/Creating-a-Makefile-that-plays-nice-with-LuaRocks

**Comment by michal-h21** [comment]
Yeah, I have simple rockspec file and Makefile for justenouhharfbuzz on my
home computer, I can post it later.

**Comment by khaledhosny** [comment]
XeTeX and all TeX engines in TeX Live statically link their dependencies, so there is no separate HarfBuzz library to use.

**Comment by deepakjois** [comment]
@khaledhosny, There seems to be Harfbuzz in the TeXLive source tree here: https://www.tug.org/svn/texlive/trunk/Build/source/libs/harfbuzz/

What is that doing? It also seems to have been upgraded recently

**Comment by khaledhosny** [comment]
That is what XeTeX statically links, I though this issue was about dynamically linking to HarfBuzz from TeX  live. If it is about building against HarfBuzz from TeX Live tree, then you can use the existing one for sure.

**Comment by deepakjois** [comment]
The initial suggestion by @davidcarlisle was to make sure luaharfbuzz builds against whatever version of Harfbuzz exists in the TeXLive source tree.

I am guessing the idea was that then, luaharfbuzz could be packaged and bundled inside TeXLive. But thinking about TeXLive packaging is a bit premature at this stage because it is still under heavy development. I don’t want to impose too many compatibility requirements so early in the process. Moreover, the version of Harfbuzz bundled may have changed if and when we get to a point where we are ready to package luaharfbuzz with TeXLive. 

So we can revisit this requirement once things have moved further along. Keeping this ticket open in the meanwhile.

**Comment by khaledhosny** [comment]
If you use a proper build system (e.g. autotools) then building inside TeX Live is unlikely to require any changes at all.

**Comment by deepakjois** [comment]
@khaledhosny Ok, that is good to know. There is also the question of API compatibility with an older version of Harfbuzz. The version in the TeXLive tree looks like it is at 1.0.4. In the current luaharfbuzz code, I am using Harfbuzz API functions (like `hb_ot_font_set_funcs`) which may not be available in that version.

**Comment by khaledhosny** [comment]
`hb_ot_font_set_funcs` exists since 0.9.28, and the in tree version of HarfBuzz in TeX Live is usually fairly up to date, so I’d not worry about that.
