### ISSUE TITLE
Use Harfbuzz field names

### ISSUE THREAD

**Issue by michal-h21** [deepakjois/luaharfbuzz#6]
For compatibility, I think it would be better to use Harfbuzz field names in shaped nodes, instead of the shorter names. So `codepoint` instead of `gid` and so on.

**Comment by deepakjois** [comment]
Yes, that’s fine. The intial prototype was more to be able to match outputs with the Harfbuzz tool `hb-shape`, which outputs glyps info in that format. I will use the more descriptive names like `x_offset`, `y_offset`, `x_advance` and `y_advance` etc.

The name `codepoint` is a bit confusing, however. It makes me think of Unicode codepoints, when actually it is a glyph ID for the specific font. But at the same time, I am not sure if that is worth breaking compatibility.

**Comment by deepakjois** [comment]
The new `harfbuzz.shape` method returns the descriptive fields now.
